exports.wrongEmail = 1;
exports.wrongPassword = 2;
exports.wrongType =3;
exports.invalidSendMail = 4
exports.wrongPhone= 5
exports.notSubscribed = 6
exports.expiredToken = 7
exports.wrongToken = 8
exports.notAuth = 9
exports.invalidImageType = 10
