import type { Metadata } from "next";
import "@/public/assets/style/globals.css";

// components
import Header from "@/components/general/Header";
import Footer from "@/components/general/Footer";
import Loader from "@/components/general/Loader";


export const metadata: Metadata = {
  title: "HMASERV",
  description: "Generated by create next app",
};

import { getLocale, getMessages } from "next-intl/server";
import StoreProvider from "@/components/Providers/StoreProvider";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {



  

  return (
    <>
      {/* <StoreProvider> */}
      <Loader />
        <section className=" app-bg">
          <Header />
          <main className="pt-[--pages-padding] pb-10 min-h-[100vh] z-50">{children}</main>
          <Footer />
        </section>
      {/* </StoreProvider> */}
    </>
  );
}
